# Site settings
title: Johnson
email: zsfbradleyjohnson@126.com
description:
baseurl: ""
url: "https://zsfbradleyjohnson.github.io"

author:
  name     : 'Bradley Johnson'
  email    : zsfbradleyjohnson@126.com
  url      : https://zsfbradleyjohnson.github.io
  facebook : http://facebook.com/fernando.dev
  twitter  : http://twitter.com/nandomoreirame

github: https://github.com/zsfbradleyjohnson
disqus_shortname: "fernandomoreira"
google_analytics: UA-52446115-1

paginate: 2
comments: true
paginate_path: "/page/:num"

sass:
  style: :compressed
  sass_dir: _sass

# Build settings
markdown  : kramdown
permalink : /:title/
