name: Bradley Johnson
markdown: redcarpet
highlighter: pygments
github: https://www.github.com/zsfbradleyjohnson
about: 我是一个iOS开发工程师。
urls:
    - text: github
      url: https://www.github.com/zsfbradleyjohnson
baseurl: ''
